// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd97D_7wAGyKz0OuXIlU8s7iZ5_1CJwVs',
    appId: '1:569788715936:web:4060147a28eea292a60ac5',
    messagingSenderId: '569788715936',
    projectId: 'selling-food-store',
    authDomain: 'selling-food-store.firebaseapp.com',
    databaseURL: 'https://selling-food-store-default-rtdb.firebaseio.com',
    storageBucket: 'selling-food-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy5OTRyFDg2dUeLP85BNXGzSqCVJiOtmM',
    appId: '1:569788715936:android:078f3c46f66109c2a60ac5',
    messagingSenderId: '569788715936',
    projectId: 'selling-food-store',
    databaseURL: 'https://selling-food-store-default-rtdb.firebaseio.com',
    storageBucket: 'selling-food-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5BxudmIkf5rC2M1ymt_JgsXsheMszyw8',
    appId: '1:569788715936:ios:4d63ca4a9d2117aaa60ac5',
    messagingSenderId: '569788715936',
    projectId: 'selling-food-store',
    databaseURL: 'https://selling-food-store-default-rtdb.firebaseio.com',
    storageBucket: 'selling-food-store.appspot.com',
    iosBundleId: 'com.example.beautyHubAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5BxudmIkf5rC2M1ymt_JgsXsheMszyw8',
    appId: '1:569788715936:ios:f8ba4e924bee9a42a60ac5',
    messagingSenderId: '569788715936',
    projectId: 'selling-food-store',
    databaseURL: 'https://selling-food-store-default-rtdb.firebaseio.com',
    storageBucket: 'selling-food-store.appspot.com',
    iosBundleId: 'com.example.beautyHubAdmin.RunnerTests',
  );
}
